name: renovate

on:
  schedule:
    # Monday at 4:00 AM UTC
    - cron: "0 4 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
      checks: write
      statuses: write
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # v4.2.2
      - uses: renovatebot/github-action@d0714047ce271f13350ee1030ff901e39a54eef3 # v43.0.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
